//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporterr.Cadastro.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagensValidacaoCadastro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensValidacaoCadastro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporterr.Cadastro.Domain.Resources.MensagensValidacaoCadastro", typeof(MensagensValidacaoCadastro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado é inválido..
        /// </summary>
        internal static string EmailInvadio {
            get {
                return ResourceManager.GetString("EmailInvadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário não pode ser vazio..
        /// </summary>
        internal static string NomeUsuarioVazio {
            get {
                return ResourceManager.GetString("NomeUsuarioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode exceder {0} caractéres..
        /// </summary>
        internal static string QuantidadeMaximaCaracteresNome {
            get {
                return ResourceManager.GetString("QuantidadeMaximaCaracteresNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa possuir a quantidade máxima de {0} caractéres..
        /// </summary>
        internal static string QuantidadeMaximaCaracteresSenha {
            get {
                return ResourceManager.GetString("QuantidadeMaximaCaracteresSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode possuir menos de {0} caractéres..
        /// </summary>
        internal static string QuantidadeMinimaCaracteresNome {
            get {
                return ResourceManager.GetString("QuantidadeMinimaCaracteresNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa possuir a quantidade mínima de {0} caractéres..
        /// </summary>
        internal static string QuantidadeMinimaCaracteresSenha {
            get {
                return ResourceManager.GetString("QuantidadeMinimaCaracteresSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada é inválida..
        /// </summary>
        internal static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
    }
}
