// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sporterr.Locacoes.Data;

namespace Sporterr.Locacoes.Data.Migrations
{
    [DbContext(typeof(LocacoesContext))]
    [Migration("20200625222304_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Sporterr.Locacoes.Domain.Locacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHoraFimLocacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHoraInicioLocacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioLocatarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("Sporterr.Locacoes.Domain.Locacao", b =>
                {
                    b.OwnsOne("Sporterr.Locacoes.Domain.Quadra", "Quadra", b1 =>
                        {
                            b1.Property<Guid>("LocacaoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnName("QuadraId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("TempoLocacaoQuadra")
                                .HasColumnName("TempoLocacaoQuadra")
                                .HasColumnType("interval");

                            b1.Property<decimal>("ValorPorTempoLocadoQuadra")
                                .HasColumnName("ValorPorTempoLocadoQuadra")
                                .HasColumnType("numeric");

                            b1.HasKey("LocacaoId");

                            b1.ToTable("Locacoes");

                            b1.WithOwner()
                                .HasForeignKey("LocacaoId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
