name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore $SOLUTIOH_PATH
    - name: Build
      run: dotnet build $SOLUTIOH_PATH --configuration Release --no-restore
    - name: Unit tests
      run: dotnet test $SOLUTIOH_PATH --filter FullyQualifiedName~.UnitTests --no-restore --verbosity normal
    - name: Run docker containers
      run: docker-compose up -d $CONTAINERS
    - name: Integration tests
      run: dotnet test $SOLUTIOH_PATH --filter FullyQualifiedName~.IntegrationTests --no-restore --verbosity normal
